import NavBar from '@/components/layout/NavBar';
import Footer from '@/components/layout/Footer';
import '@/app/global.css';

export const metadata = {
  title: '2FC - Free Fly Company',
  description: '2FC Homepage Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="ko">
            <body>
                <header>
                    <NavBar />
                </header>
                <main>
                    {children}
                </main>
                <footer>
                    <Footer />
                </footer>
            </body>
        </html>
    );
}


