import NavBar from '@/components/layout/NavBar';
import Footer from '@/components/layout/Footer';
import '@/app/global.css';
import {hasLocale, NextIntlClientProvider} from 'next-intl';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';


export const metadata = {
  title: '2FC - Free Fly Company',
  description: '2FC Homepage Generated by Next.js',
  icons: {
    icon: "/favicon.ico"
  }
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

    return (
        <html lang={locale}>
            <body>
                <NextIntlClientProvider>
                <header>
                    <NavBar />
                </header>
                <main>
                  {children}
                </main>
                <footer>
                    <Footer />
                </footer>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}


